/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DAO.BookCatDao;
import DAO.BooksDao;
import DAO.ClientDao;
import DAO.rmi.BookCatInt;
import DAO.rmi.BooksInt;
import DAO.rmi.ClientInt;
import java.awt.Image;
import java.io.File;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.BookCat;
import models.Books;
import models.Client;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 *
 * @author Memento
 */
public class ClientForm extends javax.swing.JInternalFrame {
//ClientDao cld = new ClientDao();
//BooksDao d = new BooksDao();
//BookCatDao da = new BookCatDao();

    Registry registry;

    /**
     * Creates new form ClientForm
     *
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     */
    public ClientForm() throws RemoteException, NotBoundException {
        initComponents();
        populate_combo();
        populate_combookCat();
        this.registry = LocateRegistry.getRegistry(1300);
        registry.lookup("Books");
        registry.lookup("BookCategory");
        registry.lookup("Client");
    }

    private void clear_field() {

        reg.setText("");
        fn.setText("");
        ln.setText("");
        pn.setText("");
        el.setText("");
        cbcat.setSelectedItem(null);
        sho_path.setText("");
        Bt.setSelectedItem(null);
        bc.setSelectedItem(null);
        pic_label.setIcon(null);
    }

    private void populate_combo() throws RemoteException, NotBoundException {
        BooksDao dao = new BooksDao();

        Books b = new Books();
        List<Books> bk = dao.listAll();
        DefaultComboBoxModel cModel = (DefaultComboBoxModel) Bt.getModel();
        cModel.removeAllElements();
        bk.stream().forEach((bk1) -> {
            cModel.addElement(bk1.comboGet());
        });

    }

    private void populate_combookCat() throws RemoteException, NotBoundException {

        //       BookCat bcv = new BookCat();
        BookCatDao doa = new BookCatDao();
        List<BookCat> b = doa.listAll();
        DefaultComboBoxModel cModel = (DefaultComboBoxModel) bc.getModel();
        cModel.removeAllElements();
        b.stream().forEach((bcat) -> {
            cModel.addElement(bcat.comboGet());
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        reg = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        el = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        cbcat = new javax.swing.JComboBox<String>();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_pic = new javax.swing.JButton();
        sho_path = new javax.swing.JTextField();
        pic_label = new javax.swing.JLabel();
        Bt = new javax.swing.JComboBox();
        bc = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTb = new javax.swing.JTable();
        display = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        se = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        getContentPane().setLayout(null);

        jLabel1.setText("RegNo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 22, 36, 14);

        jLabel2.setText("FirstName:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 48, 52, 14);

        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 84, 54, 14);

        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 60, 30);

        jLabel5.setText("phone number:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 190, 73, 14);

        jLabel6.setText("category:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 280, 60, 30);
        getContentPane().add(reg);
        reg.setBounds(108, 9, 120, 30);
        getContentPane().add(fn);
        fn.setBounds(108, 45, 120, 30);
        getContentPane().add(ln);
        ln.setBounds(108, 81, 120, 30);
        getContentPane().add(el);
        el.setBounds(108, 117, 120, 30);

        pn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnActionPerformed(evt);
            }
        });
        getContentPane().add(pn);
        pn.setBounds(110, 180, 120, 30);

        cbcat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "External", "Staff", "Student" }));
        getContentPane().add(cbcat);
        cbcat.setBounds(80, 280, 130, 30);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(10, 463, 57, 30);

        jLabel7.setText("Book Category:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 390, 75, 20);

        jLabel8.setText("Book Title:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 330, 50, 30);

        btn_pic.setText("Upload");
        btn_pic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_picActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pic);
        btn_pic.setBounds(300, 160, 70, 30);
        getContentPane().add(sho_path);
        sho_path.setBounds(370, 160, 140, 30);

        pic_label.setAutoscrolls(true);
        pic_label.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(pic_label);
        pic_label.setBounds(290, 10, 220, 145);

        getContentPane().add(Bt);
        Bt.setBounds(80, 340, 130, 30);

        getContentPane().add(bc);
        bc.setBounds(80, 390, 130, 30);

        clientTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RegNo", "First Name", "Last Name", "email", "Phone N°", "Client Category", "Book Title", "Book Category", "Photo Path"
            }
        ));
        jScrollPane1.setViewportView(clientTb);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 220, 530, 100);

        display.setText("Display Data");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(290, 320, 110, 30);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 463, 67, 30);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 463, 63, 30);

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 10, 80, 30);
        getContentPane().add(se);
        se.setBounds(740, 10, 180, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Client cl = new Client();
        cl.setRegNo(reg.getText());
        cl.setFirstName(fn.getText());
        cl.setLastName(ln.getText());
        cl.setPhoneNumber(pn.getText());
        cl.setEmail(el.getText());
        cl.setBookCategory(bc.getSelectedItem().toString());
        cl.setCategory(cbcat.getSelectedItem().toString());
        cl.setBookTitle(Bt.getSelectedItem().toString());
        cl.setPhoto(sho_path.getText());
        ClientDao dao = new ClientDao();
        dao.insertData(cl);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btn_picActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_picActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        String fileName = f.getAbsolutePath();
        sho_path.setText(fileName);
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(fileName);
        Image pic = icon.getImage().getScaledInstance(pic_label.getWidth(), pic_label.getHeight(), Image.SCALE_DEFAULT);
        pic_label.setIcon(new ImageIcon(pic));
    }//GEN-LAST:event_btn_picActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        ClientDao dao = new ClientDao();
        List<Client> b = dao.listAll();
        DefaultTableModel m = (DefaultTableModel) clientTb.getModel();
        m.setRowCount(0);
        b.stream().map((b1) -> new Object[]{
            b1.getRegNo(), b1.getFirstName(), b1.getLastName(), b1.getEmail(),
            b1.getPhoneNumber(), b1.getCategory(), b1.getBookTitle(), b1.getBookCategory(), b1.getPhoto()}).forEach((o) -> {
            m.addRow(o);
        });
    }//GEN-LAST:event_displayActionPerformed

    private void pnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Client cl = new Client();
        cl.setFirstName(fn.getText());
        cl.setLastName(ln.getText());
        cl.setEmail(el.getText());
        cl.setPhoneNumber(pn.getText());
        cl.setCategory(cbcat.getSelectedItem().toString());
        cl.setBookTitle(Bt.getSelectedItem().toString());
        cl.setBookCategory(bc.getSelectedItem().toString());
        cl.setPhoto(sho_path.getText());
        cl.setRegNo(reg.getText());
        ClientDao dao = new ClientDao();
        dao.update(cl);
        JOptionPane.showMessageDialog(null, "Updated");
        clear_field();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Configuration con = new Configuration().configure();
        SessionFactory sf = con.buildSessionFactory();
        Session ss = sf.openSession();
        Transaction tx = ss.beginTransaction();

        Client cl = (Client) ss.load(Client.class, se.getText());
        reg.setText(cl.getRegNo());
        fn.setText(cl.getFirstName());
        ln.setText(cl.getFirstName());
        String path = cl.getPhoto();
        ImageIcon icon = new ImageIcon(path);
        Image im = icon.getImage().getScaledInstance(pic_label.getWidth(), pic_label.getHeight(), Image.SCALE_DEFAULT);
        pic_label.setIcon(new ImageIcon(im));

        tx.commit();

        ss.close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Client cl = new Client();
        ClientDao dao = new ClientDao();
        dao.deleteClient(cl);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox Bt;
    private javax.swing.JComboBox bc;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btn_pic;
    private javax.swing.JComboBox<String> cbcat;
    private javax.swing.JTable clientTb;
    private javax.swing.JButton display;
    private javax.swing.JTextField el;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ln;
    private javax.swing.JLabel pic_label;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField se;
    private javax.swing.JTextField sho_path;
    // End of variables declaration//GEN-END:variables
}
